In [27]:
import os

from tqdm import tqdm

import itertools
import warnings
warnings.filterwarnings('ignore')

from matplotlib import gridspec
import matplotlib.dates as mdates
from matplotlib.dates import DateFormatter
import matplotlib.dates as mdates
from matplotlib import cm
import matplotlib.ticker as mtick
from matplotlib.ticker import MaxNLocator


import datetime
from scipy import stats
from scipy.stats import pearsonr
import statsmodels.api as sm

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [28]:
os.getcwd()

'/Users/reneprincipe/Library/CloudStorage/GoogleDrive-rlprincipe@up.edu.ph/My Drive/Research - PhD/notebooks'

In [35]:
data_path = '../Results/'
# data_path = '/Users/reneprincipe/Library/CloudStorage/GoogleDrive-rlprincipe@up.edu.ph/My Drive/Research - PhD/Results/Resettlements/'

In [30]:
# start_date, end_date = "2012-01-01", "2024-01-28"
# date_range = pd.date_range(start=start_date, end=end_date, freq='D')

In [42]:
prov_STL = pd.read_csv(data_path + 'Provincial_STL_NTL.csv',parse_dates=True, index_col = 0)
prov_STL
# resettlement_STL = pd.read_csv(data_path + 'Resettlement_STL_NTL.csv')

,Raw,Raw.1,Raw.2,Raw.3,Raw.4,Raw.5,Raw.6,Raw.7,Raw.8,Raw.9,...,Residual.6,Residual.7,Residual.8,Residual.9,Residual.10,Residual.11,Residual.12,Residual.13,Residual.14,Residual.15
NaT,Leyte,Iloilo,Antique,Cebu,Samar,Compostela,Misamis Oriental,Negros Occidental,Albay,Aklan,...,Misamis Oriental,Negros Occidental,Albay,Aklan,Biliran,Davao Oriental,Capiz,Lanao Del Norte,Bulacan,Laguna
2012-01-01,2.52231622366851,3.7855096494194767,2.373664094522149,12.542227329467499,2.275835352686197,1.880699031621833,7.64660629199385,3.154379529961418,2.6975414260721307,1.923014145109379,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2012-01-02,2.52231622366851,3.7855096494194767,2.373664094522149,12.542227329467499,2.275835352686197,1.880699031621833,7.64660629199385,3.154379529961418,2.6975414260721307,1.923014145109379,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2012-01-03,2.52231622366851,3.7855096494194767,2.373664094522149,12.542227329467499,2.275835352686197,1.880699031621833,7.64660629199385,3.154379529961418,2.6975414260721307,1.923014145109379,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2012-01-04,2.52231622366851,3.7855096494194767,2.373664094522149,12.542227329467499,2.275835352686197,1.880699031621833,7.64660629199385,3.154379529961418,2.6975414260721307,1.923014145109379,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-01-24,3.1975354977646457,5.568208120387945,3.0553839152824454,15.362459904725434,2.001791454428559,2.396612391264065,8.966415999937407,5.162883014583227,4.835657766207896,3.686214703071916,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-01-25,3.66589574455541,6.4574065079551115,2.8331178349225263,17.615223380196078,2.908190742297574,2.350866257895515,7.724245827619454,5.544758169331489,5.017404125197301,3.5611793774046467,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-01-26,3.789571325462468,7.013160719614227,4.327703184733894,18.059700035217766,3.443819131925499,2.601587290344005,8.966370390648462,5.52961911028218,4.834792714855041,3.636230171721437,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-01-27,4.081090706638269,7.013160719614227,3.71948218451696,18.059700035217766,3.858935018050485,2.392117727649862,9.70266564928532,6.439351867725809,5.60552648811716,3.888794166670433,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-01-28,4.081090706638269,7.013160719614227,3.71948218451696,18.059700035217766,3.858935018050485,2.392117727649862,9.70266564928532,6.439351867725809,5.60552648811716,3.888794166670433,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,Unnamed: 0,Raw,Raw.1,Raw.2,Raw.3,Raw.4,Raw.5,Raw.6,Raw.7,Raw.8,...,Residual.6,Residual.7,Residual.8,Residual.9,Residual.10,Residual.11,Residual.12,Residual.13,Residual.14,Residual.15
0,NaN,Leyte,Iloilo,Antique,Cebu,Samar,Compostela,Misamis Oriental,Negros Occidental,Albay,...,Misamis Oriental,Negros Occidental,Albay,Aklan,Biliran,Davao Oriental,Capiz,Lanao Del Norte,Bulacan,Laguna
1,2012-01-01,2.52231622366851,3.7855096494194767,2.373664094522149,12.542227329467499,2.275835352686197,1.880699031621833,7.64660629199385,3.154379529961418,2.6975414260721307,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2012-01-02,2.52231622366851,3.7855096494194767,2.373664094522149,12.542227329467499,2.275835352686197,1.880699031621833,7.64660629199385,3.154379529961418,2.6975414260721307,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2012-01-03,2.52231622366851,3.7855096494194767,2.373664094522149,12.542227329467499,2.275835352686197,1.880699031621833,7.64660629199385,3.154379529961418,2.6975414260721307,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2012-01-04,2.52231622366851,3.7855096494194767,2.373664094522149,12.542227329467499,2.275835352686197,1.880699031621833,7.64660629199385,3.154379529961418,2.6975414260721307,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4407,2024-01-24,3.1975354977646457,5.568208120387945,3.0553839152824454,15.362459904725434,2.001791454428559,2.396612391264065,8.966415999937407,5.162883014583227,4.835657766207896,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4408,2024-01-25,3.66589574455541,6.4574065079551115,2.8331178349225263,17.615223380196078,2.908190742297574,2.350866257895515,7.724245827619454,5.544758169331489,5.017404125197301,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4409,2024-01-26,3.789571325462468,7.013160719614227,4.327703184733894,18.059700035217766,3.443819131925499,2.601587290344005,8.966370390648462,5.52961911028218,4.834792714855041,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4410,2024-01-27,4.081090706638269,7.013160719614227,3.71948218451696,18.059700035217766,3.858935018050485,2.392117727649862,9.70266564928532,6.439351867725809,5.60552648811716,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4411,2024-01-28,4.081090706638269,7.013160719614227,3.71948218451696,18.059700035217766,3.858935018050485,2.392117727649862,9.70266564928532,6.439351867725809,5.60552648811716,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
path = '/Users/reneprincipe/Library/CloudStorage/GoogleDrive-rlprincipe@up.edu.ph/My Drive/Research - PhD/Results/Provincial_STL_NTL.csv'

In [33]:
pd.read_csv(path)

,Unnamed: 0,Raw,Raw.1,Raw.2,Raw.3,Raw.4,Raw.5,Raw.6,Raw.7,Raw.8,...,Residual.6,Residual.7,Residual.8,Residual.9,Residual.10,Residual.11,Residual.12,Residual.13,Residual.14,Residual.15
0,NaN,Leyte,Iloilo,Antique,Cebu,Samar,Compostela,Misamis Oriental,Negros Occidental,Albay,...,Misamis Oriental,Negros Occidental,Albay,Aklan,Biliran,Davao Oriental,Capiz,Lanao Del Norte,Bulacan,Laguna
1,2012-01-01,2.52231622366851,3.7855096494194767,2.373664094522149,12.542227329467499,2.275835352686197,1.880699031621833,7.64660629199385,3.154379529961418,2.6975414260721307,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2012-01-02,2.52231622366851,3.7855096494194767,2.373664094522149,12.542227329467499,2.275835352686197,1.880699031621833,7.64660629199385,3.154379529961418,2.6975414260721307,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2012-01-03,2.52231622366851,3.7855096494194767,2.373664094522149,12.542227329467499,2.275835352686197,1.880699031621833,7.64660629199385,3.154379529961418,2.6975414260721307,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2012-01-04,2.52231622366851,3.7855096494194767,2.373664094522149,12.542227329467499,2.275835352686197,1.880699031621833,7.64660629199385,3.154379529961418,2.6975414260721307,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4407,2024-01-24,3.1975354977646457,5.568208120387945,3.0553839152824454,15.362459904725434,2.001791454428559,2.396612391264065,8.966415999937407,5.162883014583227,4.835657766207896,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4408,2024-01-25,3.66589574455541,6.4574065079551115,2.8331178349225263,17.615223380196078,2.908190742297574,2.350866257895515,7.724245827619454,5.544758169331489,5.017404125197301,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4409,2024-01-26,3.789571325462468,7.013160719614227,4.327703184733894,18.059700035217766,3.443819131925499,2.601587290344005,8.966370390648462,5.52961911028218,4.834792714855041,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4410,2024-01-27,4.081090706638269,7.013160719614227,3.71948218451696,18.059700035217766,3.858935018050485,2.392117727649862,9.70266564928532,6.439351867725809,5.60552648811716,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4411,2024-01-28,4.081090706638269,7.013160719614227,3.71948218451696,18.059700035217766,3.858935018050485,2.392117727649862,9.70266564928532,6.439351867725809,5.60552648811716,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN